/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

/**
 *
 * @author Personal
 */
public class Clientes1 extends javax.swing.JPanel {

    /**
     * Creates new form Usuarios
     */
    public Clientes1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rSButtonIconOne2 = new RSMaterialComponent.RSButtonIconOne();
        rSTextFieldMaterialIcon1 = new RSMaterialComponent.RSTextFieldMaterialIcon();
        rSButtonIconOne3 = new RSMaterialComponent.RSButtonIconOne();
        jScrollPane2 = new javax.swing.JScrollPane();
        rSTableMetroCustom1 = new RSMaterialComponent.RSTableMetroCustom();
        rSButtonIconOne1 = new RSMaterialComponent.RSButtonIconOne();

        setPreferredSize(new java.awt.Dimension(1293, 690));

        rSButtonIconOne2.setBackground(new java.awt.Color(29, 30, 51));
        rSButtonIconOne2.setBackgroundHover(new java.awt.Color(41, 38, 76));
        rSButtonIconOne2.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.ADD);

        rSTextFieldMaterialIcon1.setForeground(new java.awt.Color(29, 30, 51));
        rSTextFieldMaterialIcon1.setColorIcon(new java.awt.Color(29, 30, 51));
        rSTextFieldMaterialIcon1.setColorMaterial(new java.awt.Color(29, 30, 51));
        rSTextFieldMaterialIcon1.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SEARCH);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("vista/Bundle"); // NOI18N
        rSTextFieldMaterialIcon1.setPlaceholder(bundle.getString("Clientes1.rSTextFieldMaterialIcon1.placeholder")); // NOI18N

        rSButtonIconOne3.setBackground(new java.awt.Color(29, 30, 51));
        rSButtonIconOne3.setBackgroundHover(new java.awt.Color(41, 38, 76));
        rSButtonIconOne3.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.RATE_REVIEW);

        rSTableMetroCustom1.setForeground(new java.awt.Color(29, 30, 51));
        rSTableMetroCustom1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"01", null, null, null, null},
                {"02", null, null, null, null},
                {"03", null, null, null, null},
                {"04", null, null, null, null},
                {"05", null, null, null, null},
                {"06", null, null, null, null},
                {"07", null, null, null, null},
                {"08", null, null, null, null},
                {"09", null, null, null, null},
                {"10", null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Telefono", "Correo", "Direccion"
            }
        ));
        rSTableMetroCustom1.setBackgoundHead(new java.awt.Color(29, 30, 51));
        rSTableMetroCustom1.setBackgoundHover(new java.awt.Color(255, 255, 255));
        rSTableMetroCustom1.setColorBorderHead(new java.awt.Color(255, 255, 255));
        rSTableMetroCustom1.setColorBorderRows(new java.awt.Color(255, 255, 255));
        rSTableMetroCustom1.setColorPrimary(new java.awt.Color(29, 30, 51));
        rSTableMetroCustom1.setColorPrimaryText(new java.awt.Color(255, 255, 255));
        rSTableMetroCustom1.setColorSecondary(new java.awt.Color(29, 30, 51));
        rSTableMetroCustom1.setColorSecundaryText(new java.awt.Color(255, 255, 255));
        rSTableMetroCustom1.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(rSTableMetroCustom1);

        rSButtonIconOne1.setBackground(new java.awt.Color(29, 30, 51));
        rSButtonIconOne1.setBackgroundHover(new java.awt.Color(41, 38, 76));
        rSButtonIconOne1.setIconTextGap(3);
        rSButtonIconOne1.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.FORMAT_LIST_BULLETED);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(202, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rSButtonIconOne1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(rSTextFieldMaterialIcon1, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(107, 107, 107)
                        .addComponent(rSButtonIconOne3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rSButtonIconOne2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 663, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(121, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(rSButtonIconOne1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(rSButtonIconOne2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(rSButtonIconOne3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(rSTextFieldMaterialIcon1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private RSMaterialComponent.RSButtonIconOne rSButtonIconOne1;
    private RSMaterialComponent.RSButtonIconOne rSButtonIconOne2;
    private RSMaterialComponent.RSButtonIconOne rSButtonIconOne3;
    private RSMaterialComponent.RSTableMetroCustom rSTableMetroCustom1;
    private RSMaterialComponent.RSTextFieldMaterialIcon rSTextFieldMaterialIcon1;
    // End of variables declaration//GEN-END:variables
}
