/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

/**
 *
 * @author Personal
 */
public class Clientes1 extends javax.swing.JPanel {

    /**
     * Creates new form Usuarios
     */
    public Clientes1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        Tabla1 = new RSMaterialComponent.RSTableMetroCustom();
        txtBuscar = new RSMaterialComponent.RSTextFieldMaterialIcon();
        btnNuevo = new rojeru_san.RSButtonRiple();
        btnNuevo1 = new rojeru_san.RSButtonRiple();
        btnNuevo2 = new rojeru_san.RSButtonRiple();
        jPanel1 = new javax.swing.JPanel();
        btnNuevo3 = new rojeru_san.RSButtonRiple();
        btnNuevo4 = new rojeru_san.RSButtonRiple();

        setBackground(new java.awt.Color(228, 233, 247));
        setPreferredSize(new java.awt.Dimension(1293, 690));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Tabla1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Tabla1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#", "tipo_cedula", "Numero", "Nombre", "Apellido", "Correo", "Telefono", "Direccion"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        Tabla1.setBackgoundHead(new java.awt.Color(29, 30, 51));
        Tabla1.setBackgoundHover(new java.awt.Color(29, 30, 51));
        Tabla1.setColorPrimaryText(new java.awt.Color(0, 0, 0));
        Tabla1.setColorSecundaryText(new java.awt.Color(0, 0, 0));
        Tabla1.setSelectionBackground(new java.awt.Color(29, 30, 91));
        jScrollPane2.setViewportView(Tabla1);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("{bundleNameSlashes}"); // NOI18N
        if (Tabla1.getColumnModel().getColumnCount() > 0) {
            Tabla1.getColumnModel().getColumn(0).setHeaderValue(bundle.getString("Clientes1.Tabla1.columnModel.title0")); // NOI18N
            Tabla1.getColumnModel().getColumn(1).setHeaderValue(bundle.getString("Clientes1.Tabla1.columnModel.title1")); // NOI18N
            Tabla1.getColumnModel().getColumn(2).setHeaderValue(bundle.getString("Clientes1.Tabla1.columnModel.title2")); // NOI18N
            Tabla1.getColumnModel().getColumn(3).setHeaderValue(bundle.getString("Clientes1.Tabla1.columnModel.title3")); // NOI18N
            Tabla1.getColumnModel().getColumn(4).setHeaderValue(bundle.getString("Clientes1.Tabla1.columnModel.title4")); // NOI18N
            Tabla1.getColumnModel().getColumn(5).setHeaderValue(bundle.getString("Clientes1.Tabla1.columnModel.title5")); // NOI18N
        }

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 1180, 470));

        txtBuscar.setForeground(new java.awt.Color(0, 0, 0));
        txtBuscar.setColorIcon(new java.awt.Color(0, 0, 0));
        txtBuscar.setColorMaterial(new java.awt.Color(153, 153, 153));
        txtBuscar.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SEARCH);
        txtBuscar.setPhColor(new java.awt.Color(102, 102, 102));
        java.util.ResourceBundle bundle1 = java.util.ResourceBundle.getBundle("vista/Bundle"); // NOI18N
        txtBuscar.setPlaceholder(bundle1.getString("Clientes1.txtBuscar.placeholder")); // NOI18N
        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });
        add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 90, 440, 40));

        btnNuevo.setBackground(new java.awt.Color(46, 49, 82));
        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/plus (2).png"))); // NOI18N
        btnNuevo.setText(bundle1.getString("Clientes1.btnNuevo.text")); // NOI18N
        btnNuevo.setFont(new java.awt.Font("Roboto Bold", 1, 16)); // NOI18N
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 640, 110, 40));

        btnNuevo1.setBackground(new java.awt.Color(46, 49, 82));
        btnNuevo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/plus (2).png"))); // NOI18N
        btnNuevo1.setText(bundle1.getString("Clientes1.btnNuevo1.text")); // NOI18N
        btnNuevo1.setFont(new java.awt.Font("Roboto Bold", 1, 16)); // NOI18N
        btnNuevo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevo1ActionPerformed(evt);
            }
        });
        add(btnNuevo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 110, 110, 30));

        btnNuevo2.setBackground(new java.awt.Color(46, 49, 82));
        btnNuevo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/plus (2).png"))); // NOI18N
        btnNuevo2.setText(bundle1.getString("Clientes1.btnNuevo2.text")); // NOI18N
        btnNuevo2.setFont(new java.awt.Font("Roboto Bold", 1, 16)); // NOI18N
        btnNuevo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevo2ActionPerformed(evt);
            }
        });
        add(btnNuevo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 640, 110, 40));

        jPanel1.setBackground(new java.awt.Color(29, 30, 51));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 640, 50, 40));

        btnNuevo3.setBackground(new java.awt.Color(46, 49, 82));
        btnNuevo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/plus (2).png"))); // NOI18N
        btnNuevo3.setText(bundle1.getString("Clientes1.btnNuevo3.text")); // NOI18N
        btnNuevo3.setFont(new java.awt.Font("Roboto Bold", 1, 16)); // NOI18N
        btnNuevo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevo3ActionPerformed(evt);
            }
        });
        add(btnNuevo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 110, 30));

        btnNuevo4.setBackground(new java.awt.Color(46, 49, 82));
        btnNuevo4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/plus (2).png"))); // NOI18N
        btnNuevo4.setText(bundle1.getString("Clientes1.btnNuevo4.text")); // NOI18N
        btnNuevo4.setFont(new java.awt.Font("Roboto Bold", 1, 16)); // NOI18N
        btnNuevo4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevo4ActionPerformed(evt);
            }
        });
        add(btnNuevo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 110, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnNuevo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevo1ActionPerformed

    private void btnNuevo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevo2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevo2ActionPerformed

    private void btnNuevo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevo3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevo3ActionPerformed

    private void btnNuevo4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevo4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevo4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private RSMaterialComponent.RSTableMetroCustom Tabla1;
    private rojeru_san.RSButtonRiple btnNuevo;
    private rojeru_san.RSButtonRiple btnNuevo1;
    private rojeru_san.RSButtonRiple btnNuevo2;
    private rojeru_san.RSButtonRiple btnNuevo3;
    private rojeru_san.RSButtonRiple btnNuevo4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private RSMaterialComponent.RSTextFieldMaterialIcon txtBuscar;
    // End of variables declaration//GEN-END:variables
}
