/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;


import controlador.Ctrl_Usuarios;

import javax.swing.JOptionPane;
import modelo.Consulta_Usuarios;


/**
 *
 * @author Personal
 */
public class Contrasena extends javax.swing.JFrame {
  public Contrasena() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setTitle("CARPINTERIA JOSE ABEL");
  }
    /**
     * Creates new form Contrasena
     */


    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        rSButton1 = new rojeru_san.RSButton();
        jLabel8 = new javax.swing.JLabel();
        txtcorreo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(29, 30, 51));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel9.setBackground(new java.awt.Color(29, 30, 51));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 35)); // NOI18N

        txt_usuario1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_usuario1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txt_usuario1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_usuario1MousePressed(evt);
            }
        });
        txt_usuario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_usuario1ActionPerformed(evt);
            }
        });
        jPanel9.add(txt_usuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 420, 40));

        login.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        login.setText("Continuar");
        login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginMouseClicked(evt);
            }
        });
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        jPanel9.add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 380, 160, 50));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 41)); // NOI18N

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Restablece la contraseña");
        jPanel9.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 450, 80));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText(" que te enviemos un codigo de seguridad.");
        jPanel9.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 500, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Volver al inicio de sesion");
        jPanel9.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 490, 230, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("Escribe el correo electronico de tu cuenta para ");
        jPanel9.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 500, 30));

        rSButton1.setBackground(new java.awt.Color(153, 153, 153));
        rSButton1.setText("Continuar");
        rSButton1.setColorHover(new java.awt.Color(0, 112, 192));
        rSButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                rSButton1MouseEntered(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                rSButton1MouseReleased(evt);
            }
        });
        rSButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButton1ActionPerformed(evt);
            }
        });
        jPanel9.add(rSButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 490, 40));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Dirección de correo electrónico");
        jPanel9.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 230, 30));
        jPanel9.add(txtcorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 490, 50));

        jPanel8.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 520, 540));

        getContentPane().add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, 590, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rSButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButton1ActionPerformed
   if (txtcorreo == null) {
            System.out.println("ERROR: txtcorreo es NULL.");
            return;
        }
        
        String correo = txtcorreo.getText().trim();
        System.out.println("Correo ingresado: '" + correo + "'");

        if (correo.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, ingrese un correo válido.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Ctrl_Usuarios ctrl = new Ctrl_Usuarios();
        Consulta_Usuarios consulta_Usuarios = new Consulta_Usuarios();
        String usuario = consulta_Usuarios.obtenerUsuarioDesdeCorreo(correo);

        if (usuario != null) {
            boolean enviado = ctrl.enviarCodigoRecuperacion(usuario, correo);
            if (enviado) {
                txtcorreo.setText("");
                JOptionPane.showMessageDialog(this, "Código enviado con éxito.");
            } else {
                JOptionPane.showMessageDialog(this, "No se pudo enviar el código.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "El correo no está registrado.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    
    }//GEN-LAST:event_rSButton1ActionPerformed

    private void rSButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSButton1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButton1MouseEntered

    private void rSButton1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSButton1MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButton1MouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Contrasena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Contrasena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Contrasena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Contrasena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Contrasena().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private rojeru_san.RSButton rSButton1;
    private javax.swing.JTextField txtcorreo;
    // End of variables declaration//GEN-END:variables
}
