/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

/**
 *
 * @author Personal
 */
public class CrearUsuario extends javax.swing.JPanel {

    /**
     * Creates new form CrearCliente
     */
    public CrearUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        rSButton2 = new rojeru_san.RSButton();
        rSButton1 = new rojeru_san.RSButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        rSTextFieldMaterial1 = new RSMaterialComponent.RSTextFieldMaterial();
        rSTextFieldMaterial2 = new RSMaterialComponent.RSTextFieldMaterial();
        rSTextFieldMaterial3 = new RSMaterialComponent.RSTextFieldMaterial();

        jLabel2.setText("jLabel2");

        setBackground(new java.awt.Color(228, 233, 247));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(228, 233, 247));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSButton2.setBackground(new java.awt.Color(67, 94, 190));
        rSButton2.setText("Guardar");
        rSButton2.setColorHover(new java.awt.Color(0, 153, 0));
        rSButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(rSButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 400, 110, -1));

        rSButton1.setBackground(new java.awt.Color(145, 152, 158));
        rSButton1.setText("Cancelar");
        rSButton1.setColorHover(new java.awt.Color(204, 0, 0));
        jPanel1.add(rSButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 400, 110, -1));

        jLabel3.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 18)); // NOI18N
        jLabel3.setText("Apellido");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 30, 70, 30));

        jLabel5.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 16)); // NOI18N
        jLabel5.setText("Correo Electronico");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 18)); // NOI18N
        jLabel6.setText("Telefono");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 200, 120, 30));

        jLabel7.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 18)); // NOI18N
        jLabel7.setText("Nombre");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 70, 30));

        jLabel8.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 18)); // NOI18N
        jLabel8.setText("Usuario");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 110, 70, 30));

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 18)); // NOI18N
        jLabel9.setText("Contraseña");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 120, 30));

        rSTextFieldMaterial1.setForeground(new java.awt.Color(29, 30, 51));
        rSTextFieldMaterial1.setCaretColor(new java.awt.Color(29, 30, 51));
        rSTextFieldMaterial1.setColorMaterial(new java.awt.Color(29, 30, 51));
        rSTextFieldMaterial1.setPhColor(new java.awt.Color(29, 30, 51));
        rSTextFieldMaterial1.setPlaceholder("Ingrese el nombre");
        rSTextFieldMaterial1.setSelectionColor(new java.awt.Color(29, 30, 51));
        jPanel1.add(rSTextFieldMaterial1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 380, -1));

        rSTextFieldMaterial2.setForeground(new java.awt.Color(29, 30, 51));
        rSTextFieldMaterial2.setCaretColor(new java.awt.Color(29, 30, 51));
        rSTextFieldMaterial2.setColorMaterial(new java.awt.Color(29, 30, 51));
        rSTextFieldMaterial2.setPhColor(new java.awt.Color(29, 30, 51));
        rSTextFieldMaterial2.setPlaceholder("Ingrese el nombre");
        rSTextFieldMaterial2.setSelectionColor(new java.awt.Color(29, 30, 51));
        jPanel1.add(rSTextFieldMaterial2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 380, -1));

        rSTextFieldMaterial3.setForeground(new java.awt.Color(29, 30, 51));
        rSTextFieldMaterial3.setCaretColor(new java.awt.Color(29, 30, 51));
        rSTextFieldMaterial3.setColorMaterial(new java.awt.Color(29, 30, 51));
        rSTextFieldMaterial3.setPhColor(new java.awt.Color(29, 30, 51));
        rSTextFieldMaterial3.setPlaceholder("Ingrese el nombre");
        rSTextFieldMaterial3.setSelectionColor(new java.awt.Color(29, 30, 51));
        jPanel1.add(rSTextFieldMaterial3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 380, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 880, 450));
    }// </editor-fold>//GEN-END:initComponents

    private void rSButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private rojeru_san.RSButton rSButton1;
    private rojeru_san.RSButton rSButton2;
    private RSMaterialComponent.RSTextFieldMaterial rSTextFieldMaterial1;
    private RSMaterialComponent.RSTextFieldMaterial rSTextFieldMaterial2;
    private RSMaterialComponent.RSTextFieldMaterial rSTextFieldMaterial3;
    // End of variables declaration//GEN-END:variables
}
