/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

/**
 *
 * @author pc
 */
public class formulario_usuario extends javax.swing.JPanel {

    /**
     * Creates new form formulario_usuario
     */
    public formulario_usuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        rSTextFieldMaterialIcon1 = new RSMaterialComponent.RSTextFieldMaterialIcon();
        rSTextFieldMaterialIcon2 = new RSMaterialComponent.RSTextFieldMaterialIcon();
        rSTextFieldMaterialIcon3 = new RSMaterialComponent.RSTextFieldMaterialIcon();
        rSTextFieldMaterialIcon4 = new RSMaterialComponent.RSTextFieldMaterialIcon();
        rSComboBoxMaterial1 = new RSMaterialComponent.RSComboBoxMaterial();
        rSButtonBigIcon_new1 = new newscomponents.RSButtonBigIcon_new();

        jPanel1.setBackground(new java.awt.Color(29, 30, 51));
        jPanel1.setPreferredSize(new java.awt.Dimension(1290, 730));

        rSTextFieldMaterialIcon1.setForeground(new java.awt.Color(29, 30, 91));
        rSTextFieldMaterialIcon1.setColorIcon(new java.awt.Color(29, 30, 111));
        rSTextFieldMaterialIcon1.setColorMaterial(new java.awt.Color(29, 30, 111));
        rSTextFieldMaterialIcon1.setPlaceholder("Nombre");
        rSTextFieldMaterialIcon1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSTextFieldMaterialIcon1ActionPerformed(evt);
            }
        });

        rSTextFieldMaterialIcon2.setForeground(new java.awt.Color(29, 30, 91));
        rSTextFieldMaterialIcon2.setColorIcon(new java.awt.Color(29, 30, 111));
        rSTextFieldMaterialIcon2.setColorMaterial(new java.awt.Color(29, 30, 111));
        rSTextFieldMaterialIcon2.setPlaceholder("Apellido");
        rSTextFieldMaterialIcon2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSTextFieldMaterialIcon2ActionPerformed(evt);
            }
        });

        rSTextFieldMaterialIcon3.setForeground(new java.awt.Color(29, 30, 91));
        rSTextFieldMaterialIcon3.setColorIcon(new java.awt.Color(29, 30, 111));
        rSTextFieldMaterialIcon3.setColorMaterial(new java.awt.Color(29, 30, 111));
        rSTextFieldMaterialIcon3.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.CALL);
        rSTextFieldMaterialIcon3.setPlaceholder("Telefono");
        rSTextFieldMaterialIcon3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSTextFieldMaterialIcon3ActionPerformed(evt);
            }
        });

        rSTextFieldMaterialIcon4.setForeground(new java.awt.Color(29, 30, 91));
        rSTextFieldMaterialIcon4.setColorIcon(new java.awt.Color(29, 30, 111));
        rSTextFieldMaterialIcon4.setColorMaterial(new java.awt.Color(29, 30, 111));
        rSTextFieldMaterialIcon4.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.MAIL);
        rSTextFieldMaterialIcon4.setPlaceholder("Correo");
        rSTextFieldMaterialIcon4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSTextFieldMaterialIcon4ActionPerformed(evt);
            }
        });

        rSComboBoxMaterial1.setForeground(new java.awt.Color(29, 30, 51));
        rSComboBoxMaterial1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Rol", "Administrador", "Contador", "Trabajador" }));

        rSButtonBigIcon_new1.setBackground(new java.awt.Color(29, 30, 51));
        rSButtonBigIcon_new1.setText("Foto");
        rSButtonBigIcon_new1.setBgHover(new java.awt.Color(29, 30, 31));
        rSButtonBigIcon_new1.setBgShadeHover(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(rSTextFieldMaterialIcon2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rSTextFieldMaterialIcon3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rSTextFieldMaterialIcon4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rSTextFieldMaterialIcon1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rSComboBoxMaterial1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(148, 148, 148)
                .addComponent(rSButtonBigIcon_new1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(513, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rSButtonBigIcon_new1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rSTextFieldMaterialIcon1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(rSTextFieldMaterialIcon2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rSTextFieldMaterialIcon3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(rSComboBoxMaterial1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addComponent(rSTextFieldMaterialIcon4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(370, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void rSTextFieldMaterialIcon1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSTextFieldMaterialIcon1ActionPerformed

    }//GEN-LAST:event_rSTextFieldMaterialIcon1ActionPerformed

    private void rSTextFieldMaterialIcon2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSTextFieldMaterialIcon2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSTextFieldMaterialIcon2ActionPerformed

    private void rSTextFieldMaterialIcon3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSTextFieldMaterialIcon3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSTextFieldMaterialIcon3ActionPerformed

    private void rSTextFieldMaterialIcon4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSTextFieldMaterialIcon4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSTextFieldMaterialIcon4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private newscomponents.RSButtonBigIcon_new rSButtonBigIcon_new1;
    private RSMaterialComponent.RSComboBoxMaterial rSComboBoxMaterial1;
    private RSMaterialComponent.RSTextFieldMaterialIcon rSTextFieldMaterialIcon1;
    private RSMaterialComponent.RSTextFieldMaterialIcon rSTextFieldMaterialIcon2;
    private RSMaterialComponent.RSTextFieldMaterialIcon rSTextFieldMaterialIcon3;
    private RSMaterialComponent.RSTextFieldMaterialIcon rSTextFieldMaterialIcon4;
    // End of variables declaration//GEN-END:variables
}
