/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Image;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author ZenBook
 */
public class Inventario extends javax.swing.JPanel {

    /**
     * Creates new form Inventario
     */
    public Inventario() {

        initComponents();
        this.btnMateriales.setSelected(true);
        
        materiales es = new materiales();
        es.setSize(890,690 );
        es.setLocation(0,0);
        
        panelprinicpal.removeAll();
        panelprinicpal.add(es, BorderLayout.CENTER);
        panelprinicpal.revalidate();
        panelprinicpal.repaint();
      
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnMateriales = new rojeru_san.RSButtonRiple();
        txtBuscar = new RSMaterialComponent.RSTextFieldMaterialIcon();
        btnHerramientas = new rojeru_san.RSButtonRiple();
        btnProductos = new rojeru_san.RSButtonRiple();
        btnMovimientos = new rojeru_san.RSButtonRiple();
        btnNuevo = new rojeru_san.RSButtonRiple();
        panelprinicpal = new javax.swing.JPanel();

        setBackground(new java.awt.Color(228, 233, 247));
        setToolTipText("");
        setMaximumSize(new java.awt.Dimension(32767, 32));
        setPreferredSize(new java.awt.Dimension(1015, 690));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnMateriales.setBackground(new java.awt.Color(0, 0, 0));
        btnMateriales.setIcon(new javax.swing.ImageIcon(getClass().getResource("/box.png"))); // NOI18N
        btnMateriales.setText("  Materiales");
        btnMateriales.setFont(new java.awt.Font("Roboto Bold", 1, 16)); // NOI18N
        btnMateriales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMaterialesActionPerformed(evt);
            }
        });
        add(btnMateriales, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 170, -1));

        txtBuscar.setForeground(new java.awt.Color(0, 0, 0));
        txtBuscar.setColorIcon(new java.awt.Color(0, 0, 0));
        txtBuscar.setColorMaterial(new java.awt.Color(153, 153, 153));
        txtBuscar.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SEARCH);
        txtBuscar.setPhColor(new java.awt.Color(102, 102, 102));
        txtBuscar.setPlaceholder("Buscar...");
        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });
        add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 357, -1));

        btnHerramientas.setBackground(new java.awt.Color(0, 0, 0));
        btnHerramientas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wrench.png"))); // NOI18N
        btnHerramientas.setText("  Herramientas");
        btnHerramientas.setFont(new java.awt.Font("Roboto Bold", 1, 16)); // NOI18N
        btnHerramientas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHerramientasActionPerformed(evt);
            }
        });
        add(btnHerramientas, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, 180, -1));

        btnProductos.setBackground(new java.awt.Color(0, 0, 0));
        btnProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tienda-de-comestibles.png"))); // NOI18N
        btnProductos.setText("  Productos terminados");
        btnProductos.setToolTipText("");
        btnProductos.setFont(new java.awt.Font("Roboto Bold", 1, 16)); // NOI18N
        btnProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductosActionPerformed(evt);
            }
        });
        add(btnProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, 250, -1));

        btnMovimientos.setBackground(new java.awt.Color(0, 0, 0));
        btnMovimientos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/transfer.png"))); // NOI18N
        btnMovimientos.setText("  Movimientos");
        btnMovimientos.setFont(new java.awt.Font("Roboto Bold", 1, 16)); // NOI18N
        btnMovimientos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMovimientosActionPerformed(evt);
            }
        });
        add(btnMovimientos, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 30, 180, -1));

        btnNuevo.setBackground(new java.awt.Color(46, 49, 82));
        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/plus (2).png"))); // NOI18N
        btnNuevo.setText(" Nuevo");
        btnNuevo.setFont(new java.awt.Font("Roboto Bold", 1, 16)); // NOI18N
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 110, 130, -1));

        panelprinicpal.setPreferredSize(new java.awt.Dimension(1000, 490));
        add(panelprinicpal, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));
    }// </editor-fold>//GEN-END:initComponents
    
    
    private void btnMaterialesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaterialesActionPerformed
        // TODO add your handling code here:
         if(!this.btnMateriales.isSelected()) {
    this.btnMateriales.setSelected(true);   
   this.btnHerramientas.setSelected(false);
      this.btnProductos.setSelected(false);
      this.btnMovimientos.setSelected(false);
        

         }
    }//GEN-LAST:event_btnMaterialesActionPerformed

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void btnHerramientasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHerramientasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHerramientasActionPerformed

    private void btnProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProductosActionPerformed

    private void btnMovimientosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMovimientosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMovimientosActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojeru_san.RSButtonRiple btnHerramientas;
    private rojeru_san.RSButtonRiple btnMateriales;
    private rojeru_san.RSButtonRiple btnMovimientos;
    private rojeru_san.RSButtonRiple btnNuevo;
    private rojeru_san.RSButtonRiple btnProductos;
    private javax.swing.JPanel panelprinicpal;
    private RSMaterialComponent.RSTextFieldMaterialIcon txtBuscar;
    // End of variables declaration//GEN-END:variables


}

